# Generated by Django 5.2.12 on 2026-04-05 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConstraintType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('instructions', models.TextField()),
                ('pedagogical_goal', models.CharField(max_length=255)),
                ('grammar_focus', models.CharField(blank=True, max_length=100)),
                ('writing_function', models.CharField(blank=True, max_length=100)),
                ('difficulty_score', models.PositiveSmallIntegerField(default=1)),
                ('word_count_min', models.PositiveSmallIntegerField()),
                ('word_count_max', models.PositiveSmallIntegerField()),
                ('estimated_time_minutes', models.PositiveSmallIntegerField()),
                ('tone', models.CharField(blank=True, max_length=50)),
                ('rotation_group', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['level__sort_order', 'exercise_type__name', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='OutputFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Constraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('constraint_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='constraints', to='fluency.constrainttype')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='constraints', to='fluency.level')),
            ],
            options={
                'ordering': ['level__sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseConstraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constraint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_constraints', to='fluency.constraint')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_constraints', to='fluency.exercise')),
            ],
            options={
                'ordering': ['exercise', 'constraint'],
            },
        ),
        migrations.AddField(
            model_name='exercise',
            name='constraints',
            field=models.ManyToManyField(blank=True, related_name='exercises', through='fluency.ExerciseConstraint', to='fluency.constraint'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='exercise_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exercises', to='fluency.exercisetype'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exercises', to='fluency.level'),
        ),
        migrations.CreateModel(
            name='DailyChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_challenges', to='fluency.exercise')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_challenges', to='fluency.level')),
            ],
            options={
                'ordering': ['-challenge_date', 'level__sort_order'],
            },
        ),
        migrations.AddField(
            model_name='exercisetype',
            name='default_output_format',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_types', to='fluency.outputformat'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='output_format',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exercises', to='fluency.outputformat'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exercises', to='fluency.topic'),
        ),
        migrations.AddConstraint(
            model_name='exerciseconstraint',
            constraint=models.UniqueConstraint(fields=('exercise', 'constraint'), name='unique_exercise_constraint'),
        ),
        migrations.AddConstraint(
            model_name='dailychallenge',
            constraint=models.UniqueConstraint(fields=('challenge_date', 'level'), name='unique_daily_challenge_per_level'),
        ),
        migrations.AddConstraint(
            model_name='constraint',
            constraint=models.UniqueConstraint(fields=('level', 'slug'), name='unique_constraint_per_level'),
        ),
        migrations.AddConstraint(
            model_name='exercise',
            constraint=models.CheckConstraint(condition=models.Q(('word_count_max__gte', models.F('word_count_min'))), name='exercise_word_count_range_valid'),
        ),
    ]
