# Generated by Django 5.2.12 on 2026-04-05 03:26

from django.db import migrations


def seed_catalog(apps, schema_editor):
    Level = apps.get_model('fluency', 'Level')
    OutputFormat = apps.get_model('fluency', 'OutputFormat')
    ExerciseType = apps.get_model('fluency', 'ExerciseType')
    ConstraintType = apps.get_model('fluency', 'ConstraintType')
    Constraint = apps.get_model('fluency', 'Constraint')
    Topic = apps.get_model('fluency', 'Topic')

    for level_data in [
        {'code': 'A1', 'name': 'Beginner', 'description': 'Guided writing with simple sentences and familiar topics.', 'sort_order': 1},
        {'code': 'A2', 'name': 'Elementary', 'description': 'Short connected writing with simple opinions and comparisons.', 'sort_order': 2},
        {'code': 'B1', 'name': 'Intermediate', 'description': 'Independent writing with clearer organization and more range.', 'sort_order': 3},
    ]:
        Level.objects.update_or_create(code=level_data['code'], defaults={**level_data, 'is_active': True})

    for output_format_data in [
        {'name': '3 sentences', 'slug': 'three-sentences', 'description': 'A very short guided response.'},
        {'name': 'Short paragraph', 'slug': 'short-paragraph', 'description': 'A compact paragraph with a few connected ideas.'},
        {'name': '5-sentence paragraph', 'slug': 'five-sentence-paragraph', 'description': 'A structured paragraph with five sentences.'},
        {'name': 'Email', 'slug': 'email', 'description': 'A simple email with greeting, body, and closing.'},
        {'name': 'Mini journal', 'slug': 'mini-journal', 'description': 'A short reflective journal entry.'},
        {'name': 'Comparison paragraph', 'slug': 'comparison-paragraph', 'description': 'A short paragraph comparing two options.'},
        {'name': 'Corrected text', 'slug': 'corrected-text', 'description': 'A rewritten or improved version of a short text.'},
        {'name': 'Short story', 'slug': 'short-story', 'description': 'A brief narrative with beginning, middle, and end.'},
        {'name': 'Summary', 'slug': 'summary', 'description': 'A concise summary of main ideas.'},
    ]:
        OutputFormat.objects.update_or_create(
            slug=output_format_data['slug'],
            defaults=output_format_data,
        )

    output_formats = {
        output_format.slug: output_format
        for output_format in OutputFormat.objects.all()
    }

    for exercise_type_data in [
        {'name': 'Opinion', 'slug': 'opinion', 'description': 'Express a point of view and support it.', 'default_output_format': 'short-paragraph'},
        {'name': 'Quick Response', 'slug': 'quick-response', 'description': 'Answer a concrete prompt in a few lines.', 'default_output_format': 'three-sentences'},
        {'name': 'Compare and Choose', 'slug': 'compare-and-choose', 'description': 'Compare options and choose one.', 'default_output_format': 'comparison-paragraph'},
        {'name': 'Storytelling', 'slug': 'storytelling', 'description': 'Narrate an event or invented story.', 'default_output_format': 'short-story'},
        {'name': 'Reformulation', 'slug': 'reformulation', 'description': 'Re-express ideas in a clearer way.', 'default_output_format': 'corrected-text'},
        {'name': 'Journaling', 'slug': 'journaling', 'description': 'Reflect on a personal topic in journal form.', 'default_output_format': 'mini-journal'},
        {'name': 'Email', 'slug': 'email', 'description': 'Write a functional or personal email.', 'default_output_format': 'email'},
        {'name': 'Summary', 'slug': 'summary', 'description': 'Summarize the main points of a text or idea.', 'default_output_format': 'summary'},
        {'name': 'Description', 'slug': 'description', 'description': 'Describe people, places, routines, or objects.', 'default_output_format': 'five-sentence-paragraph'},
        {'name': 'Debate', 'slug': 'debate', 'description': 'Present and support a position in a simple debate.', 'default_output_format': 'short-paragraph'},
        {'name': 'Counterargument', 'slug': 'counterargument', 'description': 'Introduce a contrasting idea before concluding.', 'default_output_format': 'short-paragraph'},
        {'name': 'Rewrite Challenge', 'slug': 'rewrite-challenge', 'description': 'Improve a short text by rewriting it.', 'default_output_format': 'corrected-text'},
        {'name': 'Vocabulary Mission', 'slug': 'vocabulary-mission', 'description': 'Write using target vocabulary constraints.', 'default_output_format': 'short-paragraph'},
        {'name': 'Error Hunt', 'slug': 'error-hunt', 'description': 'Find and correct errors in a short text.', 'default_output_format': 'corrected-text'},
        {'name': 'Reflection', 'slug': 'reflection', 'description': 'Reflect on an idea, habit, or experience.', 'default_output_format': 'mini-journal'},
        {'name': 'Scenario Writing', 'slug': 'scenario-writing', 'description': 'Write based on a practical or imagined situation.', 'default_output_format': 'short-paragraph'},
    ]:
        default_output_format_slug = exercise_type_data.pop('default_output_format')
        ExerciseType.objects.update_or_create(
            slug=exercise_type_data['slug'],
            defaults={
                **exercise_type_data,
                'default_output_format': output_formats[default_output_format_slug],
                'is_active': True,
            },
        )

    for constraint_type_data in [
        {'name': 'Grammar', 'slug': 'grammar', 'description': 'A grammar target the learner must use.'},
        {'name': 'Vocabulary', 'slug': 'vocabulary', 'description': 'A vocabulary target or limitation.'},
        {'name': 'Structure', 'slug': 'structure', 'description': 'A structural rule for the response.'},
        {'name': 'Tone', 'slug': 'tone', 'description': 'A tone or stance requirement.'},
        {'name': 'Creativity', 'slug': 'creativity', 'description': 'A creative twist that shapes the response.'},
        {'name': 'Limitation', 'slug': 'limitation', 'description': 'A limit on length or format.'},
    ]:
        ConstraintType.objects.update_or_create(
            slug=constraint_type_data['slug'],
            defaults=constraint_type_data,
        )

    for topic_data in [
        {'name': 'Daily life', 'slug': 'daily-life', 'description': 'Routines and everyday activities.'},
        {'name': 'Family', 'slug': 'family', 'description': 'Family members and home life.'},
        {'name': 'School', 'slug': 'school', 'description': 'School routines, classes, and study.'},
        {'name': 'Work', 'slug': 'work', 'description': 'Work life and responsibilities.'},
        {'name': 'Hobbies', 'slug': 'hobbies', 'description': 'Free-time interests and activities.'},
        {'name': 'Food', 'slug': 'food', 'description': 'Meals, preferences, and food habits.'},
        {'name': 'Travel', 'slug': 'travel', 'description': 'Trips, transport, and travel plans.'},
        {'name': 'Technology', 'slug': 'technology', 'description': 'Technology use in daily life.'},
        {'name': 'Feelings', 'slug': 'feelings', 'description': 'Emotions, moods, and reactions.'},
        {'name': 'Future plans', 'slug': 'future-plans', 'description': 'Goals and upcoming plans.'},
        {'name': 'Personal habits', 'slug': 'personal-habits', 'description': 'Personal routines and habits.'},
        {'name': 'My city', 'slug': 'my-city', 'description': 'Places, people, and routines in the city.'},
        {'name': 'Learning', 'slug': 'learning', 'description': 'Study habits and learning preferences.'},
    ]:
        Topic.objects.update_or_create(slug=topic_data['slug'], defaults={**topic_data, 'is_active': True})

    levels = {level.code: level for level in Level.objects.all()}
    constraint_types = {
        constraint_type.slug: constraint_type
        for constraint_type in ConstraintType.objects.all()
    }

    for constraint_data in [
        {'level_code': 'A1', 'constraint_type': 'grammar', 'name': 'Use present simple', 'slug': 'use-present-simple', 'description': 'Use the present simple to describe routines or facts.'},
        {'level_code': 'A1', 'constraint_type': 'vocabulary', 'name': 'Use I like or I do not like', 'slug': 'use-i-like', 'description': 'Include basic preference language.'},
        {'level_code': 'A1', 'constraint_type': 'structure', 'name': 'Write 3 sentences', 'slug': 'write-3-sentences', 'description': 'Answer with exactly three sentences.'},
        {'level_code': 'A1', 'constraint_type': 'vocabulary', 'name': 'Use 3 adjectives', 'slug': 'use-3-adjectives', 'description': 'Include three descriptive adjectives.'},
        {'level_code': 'A1', 'constraint_type': 'structure', 'name': 'Answer with because', 'slug': 'answer-with-because', 'description': 'Give a reason using because.'},
        {'level_code': 'A1', 'constraint_type': 'structure', 'name': 'Write 5 sentences', 'slug': 'write-5-sentences', 'description': 'Write a short paragraph with five sentences.'},
        {'level_code': 'A2', 'constraint_type': 'structure', 'name': 'Give 2 reasons', 'slug': 'give-2-reasons', 'description': 'Support your answer with two reasons.'},
        {'level_code': 'A2', 'constraint_type': 'grammar', 'name': 'Use because, but, and so', 'slug': 'use-because-but-so', 'description': 'Connect ideas using basic linkers.'},
        {'level_code': 'A2', 'constraint_type': 'grammar', 'name': 'Use past simple', 'slug': 'use-past-simple', 'description': 'Write about a past action using past simple.'},
        {'level_code': 'A2', 'constraint_type': 'limitation', 'name': 'Write 60 to 80 words', 'slug': 'write-60-80-words', 'description': 'Keep the response inside the target range.'},
        {'level_code': 'A2', 'constraint_type': 'creativity', 'name': 'Include one example', 'slug': 'include-one-example', 'description': 'Support the answer with one concrete example.'},
        {'level_code': 'B1', 'constraint_type': 'tone', 'name': 'Defend one side', 'slug': 'defend-one-side', 'description': 'Choose a side and support it clearly.'},
        {'level_code': 'B1', 'constraint_type': 'structure', 'name': 'Include a counter idea', 'slug': 'include-a-counter-idea', 'description': 'Acknowledge an alternative perspective.'},
        {'level_code': 'B1', 'constraint_type': 'grammar', 'name': 'Use past simple and present perfect', 'slug': 'use-past-simple-and-present-perfect', 'description': 'Combine both tenses in a coherent way.'},
        {'level_code': 'B1', 'constraint_type': 'limitation', 'name': 'Write 80 to 120 words', 'slug': 'write-80-120-words', 'description': 'Write a more developed short text.'},
        {'level_code': 'B1', 'constraint_type': 'structure', 'name': 'Add a conclusion sentence', 'slug': 'add-a-conclusion-sentence', 'description': 'Finish with a closing or concluding sentence.'},
        {'level_code': 'B1', 'constraint_type': 'structure', 'name': 'Write in email format', 'slug': 'write-in-email-format', 'description': 'Use an email greeting, body, and closing.'},
    ]:
        level = levels[constraint_data['level_code']]
        constraint_type = constraint_types[constraint_data['constraint_type']]
        Constraint.objects.update_or_create(
            level=level,
            slug=constraint_data['slug'],
            defaults={
                'constraint_type': constraint_type,
                'name': constraint_data['name'],
                'description': constraint_data['description'],
                'is_active': True,
            },
        )


def unseed_catalog(apps, schema_editor):
    Level = apps.get_model('fluency', 'Level')
    OutputFormat = apps.get_model('fluency', 'OutputFormat')
    ExerciseType = apps.get_model('fluency', 'ExerciseType')
    ConstraintType = apps.get_model('fluency', 'ConstraintType')
    Constraint = apps.get_model('fluency', 'Constraint')
    Topic = apps.get_model('fluency', 'Topic')

    Constraint.objects.filter(
        slug__in=[
            'use-present-simple',
            'use-i-like',
            'write-3-sentences',
            'use-3-adjectives',
            'answer-with-because',
            'write-5-sentences',
            'give-2-reasons',
            'use-because-but-so',
            'use-past-simple',
            'write-60-80-words',
            'include-one-example',
            'defend-one-side',
            'include-a-counter-idea',
            'use-past-simple-and-present-perfect',
            'write-80-120-words',
            'add-a-conclusion-sentence',
            'write-in-email-format',
        ]
    ).delete()
    Topic.objects.filter(
        slug__in=[
            'daily-life',
            'family',
            'school',
            'work',
            'hobbies',
            'food',
            'travel',
            'technology',
            'feelings',
            'future-plans',
            'personal-habits',
            'my-city',
            'learning',
        ]
    ).delete()
    ExerciseType.objects.filter(
        slug__in=[
            'opinion',
            'quick-response',
            'compare-and-choose',
            'storytelling',
            'reformulation',
            'journaling',
            'email',
            'summary',
            'description',
            'debate',
            'counterargument',
            'rewrite-challenge',
            'vocabulary-mission',
            'error-hunt',
            'reflection',
            'scenario-writing',
        ]
    ).delete()
    ConstraintType.objects.filter(
        slug__in=['grammar', 'vocabulary', 'structure', 'tone', 'creativity', 'limitation']
    ).delete()
    OutputFormat.objects.filter(
        slug__in=[
            'three-sentences',
            'short-paragraph',
            'five-sentence-paragraph',
            'email',
            'mini-journal',
            'comparison-paragraph',
            'corrected-text',
            'short-story',
            'summary',
        ]
    ).delete()
    Level.objects.filter(code__in=['A1', 'A2', 'B1']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('fluency', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_catalog, unseed_catalog),
    ]
