# Generated by Django 5.2.12 on 2026-04-05 03:26

from django.db import migrations


def seed_exercises(apps, schema_editor):
    Constraint = apps.get_model('fluency', 'Constraint')
    DailyChallenge = apps.get_model('fluency', 'DailyChallenge')
    Exercise = apps.get_model('fluency', 'Exercise')
    ExerciseConstraint = apps.get_model('fluency', 'ExerciseConstraint')
    ExerciseType = apps.get_model('fluency', 'ExerciseType')
    Level = apps.get_model('fluency', 'Level')
    OutputFormat = apps.get_model('fluency', 'OutputFormat')
    Topic = apps.get_model('fluency', 'Topic')

    levels = {level.code: level for level in Level.objects.all()}
    exercise_types = {exercise_type.slug: exercise_type for exercise_type in ExerciseType.objects.all()}
    output_formats = {output_format.slug: output_format for output_format in OutputFormat.objects.all()}
    topics = {topic.slug: topic for topic in Topic.objects.all()}
    constraints = {
        (constraint.level.code, constraint.slug): constraint
        for constraint in Constraint.objects.select_related('level')
    }

    exercises = [
        {
            'title': 'Breakfast in three sentences',
            'instructions': 'Write three sentences about what you usually eat for breakfast and why you like it.',
            'level_code': 'A1',
            'exercise_type': 'quick-response',
            'topic': 'food',
            'output_format': 'three-sentences',
            'pedagogical_goal': 'Build simple routine sentences about food preferences.',
            'grammar_focus': 'present simple',
            'writing_function': 'describe',
            'difficulty_score': 1,
            'word_count_min': 20,
            'word_count_max': 30,
            'estimated_time_minutes': 4,
            'tone': 'personal',
            'rotation_group': 'daily_quick_response',
            'constraints': [('A1', 'write-3-sentences'), ('A1', 'answer-with-because')],
        },
        {
            'title': 'My morning routine',
            'instructions': 'Write about your morning routine from the moment you wake up until you leave home.',
            'level_code': 'A1',
            'exercise_type': 'description',
            'topic': 'daily-life',
            'output_format': 'five-sentence-paragraph',
            'pedagogical_goal': 'Practice routine vocabulary with guided sentence building.',
            'grammar_focus': 'present simple',
            'writing_function': 'describe',
            'difficulty_score': 1,
            'word_count_min': 30,
            'word_count_max': 50,
            'estimated_time_minutes': 5,
            'tone': 'personal',
            'rotation_group': 'daily_description',
            'constraints': [('A1', 'use-present-simple'), ('A1', 'write-5-sentences')],
        },
        {
            'title': 'Why I like weekends',
            'instructions': 'Write a short paragraph about why you like weekends and what you usually do.',
            'level_code': 'A1',
            'exercise_type': 'opinion',
            'topic': 'personal-habits',
            'output_format': 'short-paragraph',
            'pedagogical_goal': 'Express a basic opinion with one reason.',
            'grammar_focus': 'present simple',
            'writing_function': 'justify',
            'difficulty_score': 1,
            'word_count_min': 30,
            'word_count_max': 45,
            'estimated_time_minutes': 5,
            'tone': 'personal',
            'rotation_group': 'daily_opinion',
            'constraints': [('A1', 'use-i-like'), ('A1', 'answer-with-because')],
        },
        {
            'title': 'After school today',
            'instructions': 'Write a mini journal about what you do after school and how you feel at the end of the day.',
            'level_code': 'A1',
            'exercise_type': 'journaling',
            'topic': 'school',
            'output_format': 'mini-journal',
            'pedagogical_goal': 'Develop confidence writing about daily habits and feelings.',
            'grammar_focus': 'present simple',
            'writing_function': 'reflect',
            'difficulty_score': 1,
            'word_count_min': 30,
            'word_count_max': 45,
            'estimated_time_minutes': 5,
            'tone': 'reflective',
            'rotation_group': 'daily_reflection',
            'constraints': [('A1', 'use-3-adjectives')],
        },
        {
            'title': 'Learning English after work',
            'instructions': 'Do you think studying English after work is a good idea? Give your opinion and explain why.',
            'level_code': 'A2',
            'exercise_type': 'opinion',
            'topic': 'work',
            'output_format': 'short-paragraph',
            'pedagogical_goal': 'Support a short opinion with connected reasons.',
            'grammar_focus': 'because, but, so',
            'writing_function': 'justify',
            'difficulty_score': 2,
            'word_count_min': 60,
            'word_count_max': 80,
            'estimated_time_minutes': 8,
            'tone': 'neutral',
            'rotation_group': 'daily_opinion',
            'constraints': [('A2', 'give-2-reasons'), ('A2', 'use-because-but-so')],
        },
        {
            'title': 'Books or videos for study',
            'instructions': 'Would you rather learn English by watching videos or reading books? Choose one and explain why.',
            'level_code': 'A2',
            'exercise_type': 'compare-and-choose',
            'topic': 'learning',
            'output_format': 'comparison-paragraph',
            'pedagogical_goal': 'Compare two options and justify a preference.',
            'grammar_focus': 'because, but, so',
            'writing_function': 'compare',
            'difficulty_score': 2,
            'word_count_min': 60,
            'word_count_max': 80,
            'estimated_time_minutes': 8,
            'tone': 'neutral',
            'rotation_group': 'daily_compare',
            'constraints': [('A2', 'give-2-reasons'), ('A2', 'use-because-but-so')],
        },
        {
            'title': 'My city on the weekend',
            'instructions': 'Describe what your city is like on the weekend and mention one place you enjoy visiting.',
            'level_code': 'A2',
            'exercise_type': 'description',
            'topic': 'my-city',
            'output_format': 'short-paragraph',
            'pedagogical_goal': 'Write a clearer descriptive paragraph with supporting detail.',
            'grammar_focus': 'present simple',
            'writing_function': 'describe',
            'difficulty_score': 2,
            'word_count_min': 60,
            'word_count_max': 80,
            'estimated_time_minutes': 8,
            'tone': 'descriptive',
            'rotation_group': 'daily_description',
            'constraints': [('A2', 'write-60-80-words'), ('A2', 'include-one-example')],
        },
        {
            'title': 'Rewrite a message about yesterday',
            'instructions': 'Rewrite this idea as a clearer short message: yesterday I go to the park with my cousin and we play football and eat pizza.',
            'level_code': 'A2',
            'exercise_type': 'rewrite-challenge',
            'topic': 'daily-life',
            'output_format': 'corrected-text',
            'pedagogical_goal': 'Practice sentence correction and better control of past actions.',
            'grammar_focus': 'past simple',
            'writing_function': 'reformulate',
            'difficulty_score': 2,
            'word_count_min': 40,
            'word_count_max': 60,
            'estimated_time_minutes': 7,
            'tone': 'neutral',
            'rotation_group': 'daily_rewrite',
            'constraints': [('A2', 'use-past-simple')],
        },
        {
            'title': 'An unexpected day',
            'instructions': 'Write a short story about a day that started normally but changed in an unexpected way.',
            'level_code': 'B1',
            'exercise_type': 'storytelling',
            'topic': 'daily-life',
            'output_format': 'short-story',
            'pedagogical_goal': 'Narrate a short event with clear sequence and tense control.',
            'grammar_focus': 'past simple and present perfect',
            'writing_function': 'narrate',
            'difficulty_score': 3,
            'word_count_min': 80,
            'word_count_max': 120,
            'estimated_time_minutes': 10,
            'tone': 'narrative',
            'rotation_group': 'daily_story',
            'constraints': [('B1', 'use-past-simple-and-present-perfect'), ('B1', 'write-80-120-words')],
        },
        {
            'title': 'Email to a friend about a trip',
            'instructions': 'Write an email to a friend telling them about a recent trip and what you learned from it.',
            'level_code': 'B1',
            'exercise_type': 'email',
            'topic': 'travel',
            'output_format': 'email',
            'pedagogical_goal': 'Write a functional personal email with clear structure.',
            'grammar_focus': 'past simple',
            'writing_function': 'explain',
            'difficulty_score': 3,
            'word_count_min': 80,
            'word_count_max': 120,
            'estimated_time_minutes': 10,
            'tone': 'friendly',
            'rotation_group': 'daily_email',
            'constraints': [('B1', 'write-in-email-format'), ('B1', 'add-a-conclusion-sentence')],
        },
        {
            'title': 'Summarize a useful study tip',
            'instructions': 'Imagine you read a short article about one useful study tip. Write a brief summary of the main idea and why it matters.',
            'level_code': 'B1',
            'exercise_type': 'summary',
            'topic': 'learning',
            'output_format': 'summary',
            'pedagogical_goal': 'Condense an idea into a short organized summary.',
            'grammar_focus': 'present simple',
            'writing_function': 'summarize',
            'difficulty_score': 3,
            'word_count_min': 80,
            'word_count_max': 110,
            'estimated_time_minutes': 9,
            'tone': 'neutral',
            'rotation_group': 'daily_summary',
            'constraints': [('B1', 'add-a-conclusion-sentence')],
        },
        {
            'title': 'A skill I want to improve',
            'instructions': 'Reflect on one skill you want to improve this year, why it matters, and how you plan to work on it.',
            'level_code': 'B1',
            'exercise_type': 'reflection',
            'topic': 'future-plans',
            'output_format': 'mini-journal',
            'pedagogical_goal': 'Write a reflective text with reasons and a clear conclusion.',
            'grammar_focus': 'present simple and future reference',
            'writing_function': 'reflect',
            'difficulty_score': 3,
            'word_count_min': 80,
            'word_count_max': 120,
            'estimated_time_minutes': 10,
            'tone': 'reflective',
            'rotation_group': 'daily_reflection',
            'constraints': [('B1', 'defend-one-side'), ('B1', 'add-a-conclusion-sentence')],
        },
    ]

    for exercise_data in exercises:
        level = levels[exercise_data['level_code']]
        exercise_type = exercise_types[exercise_data['exercise_type']]
        topic = topics[exercise_data['topic']]
        output_format = output_formats[exercise_data['output_format']]
        constraint_keys = exercise_data.pop('constraints')
        title = exercise_data['title']
        exercise, _ = Exercise.objects.update_or_create(
            title=title,
            level=level,
            defaults={
                'instructions': exercise_data['instructions'],
                'exercise_type': exercise_type,
                'topic': topic,
                'output_format': output_format,
                'pedagogical_goal': exercise_data['pedagogical_goal'],
                'grammar_focus': exercise_data['grammar_focus'],
                'writing_function': exercise_data['writing_function'],
                'difficulty_score': exercise_data['difficulty_score'],
                'word_count_min': exercise_data['word_count_min'],
                'word_count_max': exercise_data['word_count_max'],
                'estimated_time_minutes': exercise_data['estimated_time_minutes'],
                'tone': exercise_data['tone'],
                'rotation_group': exercise_data['rotation_group'],
                'is_active': True,
            },
        )
        ExerciseConstraint.objects.filter(exercise=exercise).delete()
        for constraint_key in constraint_keys:
            ExerciseConstraint.objects.create(
                exercise=exercise,
                constraint=constraints[constraint_key],
            )

    DailyChallenge.objects.all().delete()


def unseed_exercises(apps, schema_editor):
    DailyChallenge = apps.get_model('fluency', 'DailyChallenge')
    Exercise = apps.get_model('fluency', 'Exercise')

    DailyChallenge.objects.all().delete()
    Exercise.objects.filter(
        title__in=[
            'Breakfast in three sentences',
            'My morning routine',
            'Why I like weekends',
            'After school today',
            'Learning English after work',
            'Books or videos for study',
            'My city on the weekend',
            'Rewrite a message about yesterday',
            'An unexpected day',
            'Email to a friend about a trip',
            'Summarize a useful study tip',
            'A skill I want to improve',
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('fluency', '0002_seed_catalog'),
    ]

    operations = [
        migrations.RunPython(seed_exercises, unseed_exercises),
    ]
