from django.db import migrations


def seed_exercises_batch_2(apps, schema_editor):
    Constraint = apps.get_model('fluency', 'Constraint')
    DailyChallenge = apps.get_model('fluency', 'DailyChallenge')
    Exercise = apps.get_model('fluency', 'Exercise')
    ExerciseConstraint = apps.get_model('fluency', 'ExerciseConstraint')
    ExerciseType = apps.get_model('fluency', 'ExerciseType')
    Level = apps.get_model('fluency', 'Level')
    OutputFormat = apps.get_model('fluency', 'OutputFormat')
    Topic = apps.get_model('fluency', 'Topic')

    levels = {level.code: level for level in Level.objects.all()}
    exercise_types = {exercise_type.slug: exercise_type for exercise_type in ExerciseType.objects.all()}
    output_formats = {output_format.slug: output_format for output_format in OutputFormat.objects.all()}
    topics = {topic.slug: topic for topic in Topic.objects.all()}
    constraints = {
        (constraint.level.code, constraint.slug): constraint
        for constraint in Constraint.objects.select_related('level')
    }

    exercises = [
        {
            'title': 'My favorite place at home',
            'instructions': 'Describe your favorite place at home and explain why you like it.',
            'level_code': 'A1',
            'exercise_type': 'description',
            'topic': 'family',
            'output_format': 'five-sentence-paragraph',
            'pedagogical_goal': 'Describe a familiar place with simple details.',
            'grammar_focus': 'present simple',
            'writing_function': 'describe',
            'difficulty_score': 1,
            'word_count_min': 30,
            'word_count_max': 50,
            'estimated_time_minutes': 5,
            'tone': 'personal',
            'rotation_group': 'daily_description',
            'constraints': [('A1', 'use-present-simple'), ('A1', 'use-3-adjectives')],
        },
        {
            'title': 'A good snack for school',
            'instructions': 'Write about a snack you think is good for school and say why you like it.',
            'level_code': 'A1',
            'exercise_type': 'opinion',
            'topic': 'food',
            'output_format': 'short-paragraph',
            'pedagogical_goal': 'Express a basic opinion about food preferences.',
            'grammar_focus': 'present simple',
            'writing_function': 'justify',
            'difficulty_score': 1,
            'word_count_min': 30,
            'word_count_max': 45,
            'estimated_time_minutes': 5,
            'tone': 'personal',
            'rotation_group': 'daily_opinion',
            'constraints': [('A1', 'use-i-like'), ('A1', 'answer-with-because')],
        },
        {
            'title': 'Three things in my bag',
            'instructions': 'Write three sentences about three things in your bag and what they are for.',
            'level_code': 'A1',
            'exercise_type': 'quick-response',
            'topic': 'school',
            'output_format': 'three-sentences',
            'pedagogical_goal': 'Build short descriptive sentences about everyday objects.',
            'grammar_focus': 'present simple',
            'writing_function': 'describe',
            'difficulty_score': 1,
            'word_count_min': 18,
            'word_count_max': 30,
            'estimated_time_minutes': 4,
            'tone': 'neutral',
            'rotation_group': 'daily_quick_response',
            'constraints': [('A1', 'write-3-sentences'), ('A1', 'use-3-adjectives')],
        },
        {
            'title': 'My best weekday habit',
            'instructions': 'Write a mini journal about one good habit you have on weekdays.',
            'level_code': 'A1',
            'exercise_type': 'journaling',
            'topic': 'personal-habits',
            'output_format': 'mini-journal',
            'pedagogical_goal': 'Write about a personal habit with simple reflection.',
            'grammar_focus': 'present simple',
            'writing_function': 'reflect',
            'difficulty_score': 1,
            'word_count_min': 30,
            'word_count_max': 45,
            'estimated_time_minutes': 5,
            'tone': 'reflective',
            'rotation_group': 'daily_reflection',
            'constraints': [('A1', 'use-present-simple')],
        },
        {
            'title': 'A family member I admire',
            'instructions': 'Describe a family member you admire and say what makes this person special.',
            'level_code': 'A1',
            'exercise_type': 'description',
            'topic': 'family',
            'output_format': 'five-sentence-paragraph',
            'pedagogical_goal': 'Describe a person using simple structure and adjectives.',
            'grammar_focus': 'present simple',
            'writing_function': 'describe',
            'difficulty_score': 1,
            'word_count_min': 30,
            'word_count_max': 50,
            'estimated_time_minutes': 5,
            'tone': 'personal',
            'rotation_group': 'daily_description',
            'constraints': [('A1', 'write-5-sentences'), ('A1', 'use-3-adjectives')],
        },
        {
            'title': 'What I do after dinner',
            'instructions': 'Write three sentences about what you usually do after dinner.',
            'level_code': 'A1',
            'exercise_type': 'quick-response',
            'topic': 'daily-life',
            'output_format': 'three-sentences',
            'pedagogical_goal': 'Practice daily routine writing with short guided output.',
            'grammar_focus': 'present simple',
            'writing_function': 'describe',
            'difficulty_score': 1,
            'word_count_min': 18,
            'word_count_max': 30,
            'estimated_time_minutes': 4,
            'tone': 'personal',
            'rotation_group': 'daily_quick_response',
            'constraints': [('A1', 'write-3-sentences'), ('A1', 'use-present-simple')],
        },
        {
            'title': 'Three words about my city',
            'instructions': 'Choose three adjectives for your city and write a short text using them.',
            'level_code': 'A1',
            'exercise_type': 'vocabulary-mission',
            'topic': 'my-city',
            'output_format': 'short-paragraph',
            'pedagogical_goal': 'Use basic city vocabulary in a short descriptive text.',
            'grammar_focus': 'present simple',
            'writing_function': 'describe',
            'difficulty_score': 1,
            'word_count_min': 25,
            'word_count_max': 40,
            'estimated_time_minutes': 5,
            'tone': 'descriptive',
            'rotation_group': 'daily_vocabulary',
            'constraints': [('A1', 'use-3-adjectives'), ('A1', 'write-3-sentences')],
        },
        {
            'title': 'A hobby I enjoy',
            'instructions': 'Write about a hobby you enjoy and explain why it is fun for you.',
            'level_code': 'A1',
            'exercise_type': 'vocabulary-mission',
            'topic': 'hobbies',
            'output_format': 'short-paragraph',
            'pedagogical_goal': 'Build hobby vocabulary and express a simple reason.',
            'grammar_focus': 'present simple',
            'writing_function': 'justify',
            'difficulty_score': 1,
            'word_count_min': 25,
            'word_count_max': 40,
            'estimated_time_minutes': 5,
            'tone': 'personal',
            'rotation_group': 'daily_vocabulary',
            'constraints': [('A1', 'use-i-like'), ('A1', 'answer-with-because')],
        },
        {
            'title': 'Study alone or with friends',
            'instructions': 'Would you rather study alone or with friends? Choose one and explain your reasons.',
            'level_code': 'A2',
            'exercise_type': 'compare-and-choose',
            'topic': 'learning',
            'output_format': 'comparison-paragraph',
            'pedagogical_goal': 'Compare learning options with connected reasons.',
            'grammar_focus': 'because, but, so',
            'writing_function': 'compare',
            'difficulty_score': 2,
            'word_count_min': 60,
            'word_count_max': 80,
            'estimated_time_minutes': 8,
            'tone': 'neutral',
            'rotation_group': 'daily_compare',
            'constraints': [('A2', 'give-2-reasons'), ('A2', 'use-because-but-so')],
        },
        {
            'title': 'A useful app for students',
            'instructions': 'Write about one app that is useful for students and explain why you recommend it.',
            'level_code': 'A2',
            'exercise_type': 'opinion',
            'topic': 'technology',
            'output_format': 'short-paragraph',
            'pedagogical_goal': 'Support an opinion with reasons and one example.',
            'grammar_focus': 'because, but, so',
            'writing_function': 'justify',
            'difficulty_score': 2,
            'word_count_min': 60,
            'word_count_max': 80,
            'estimated_time_minutes': 8,
            'tone': 'neutral',
            'rotation_group': 'daily_opinion',
            'constraints': [('A2', 'give-2-reasons'), ('A2', 'include-one-example')],
        },
        {
            'title': 'My neighborhood in the evening',
            'instructions': 'Describe your neighborhood in the evening and include one example of something people usually do.',
            'level_code': 'A2',
            'exercise_type': 'description',
            'topic': 'my-city',
            'output_format': 'short-paragraph',
            'pedagogical_goal': 'Write a more organized description of a familiar place.',
            'grammar_focus': 'present simple',
            'writing_function': 'describe',
            'difficulty_score': 2,
            'word_count_min': 60,
            'word_count_max': 80,
            'estimated_time_minutes': 8,
            'tone': 'descriptive',
            'rotation_group': 'daily_description',
            'constraints': [('A2', 'write-60-80-words'), ('A2', 'include-one-example')],
        },
        {
            'title': 'An email to invite a friend',
            'instructions': 'Write an email inviting a friend to do something with you this weekend.',
            'level_code': 'A2',
            'exercise_type': 'email',
            'topic': 'hobbies',
            'output_format': 'email',
            'pedagogical_goal': 'Practice simple functional email writing.',
            'grammar_focus': 'present simple',
            'writing_function': 'request',
            'difficulty_score': 2,
            'word_count_min': 60,
            'word_count_max': 80,
            'estimated_time_minutes': 8,
            'tone': 'friendly',
            'rotation_group': 'daily_email',
            'constraints': [('A2', 'write-60-80-words')],
        },
        {
            'title': 'A day I felt proud',
            'instructions': 'Write about a day you felt proud of yourself and explain what happened.',
            'level_code': 'A2',
            'exercise_type': 'reflection',
            'topic': 'feelings',
            'output_format': 'mini-journal',
            'pedagogical_goal': 'Reflect on a past experience with one supporting example.',
            'grammar_focus': 'past simple',
            'writing_function': 'reflect',
            'difficulty_score': 2,
            'word_count_min': 60,
            'word_count_max': 80,
            'estimated_time_minutes': 8,
            'tone': 'reflective',
            'rotation_group': 'daily_reflection',
            'constraints': [('A2', 'use-past-simple'), ('A2', 'include-one-example')],
        },
        {
            'title': 'You missed the bus',
            'instructions': 'Write about what happened when you missed the bus and what you did next.',
            'level_code': 'A2',
            'exercise_type': 'scenario-writing',
            'topic': 'daily-life',
            'output_format': 'short-paragraph',
            'pedagogical_goal': 'Narrate a simple problem and response in order.',
            'grammar_focus': 'past simple',
            'writing_function': 'narrate',
            'difficulty_score': 2,
            'word_count_min': 60,
            'word_count_max': 80,
            'estimated_time_minutes': 8,
            'tone': 'neutral',
            'rotation_group': 'daily_scenario',
            'constraints': [('A2', 'use-past-simple'), ('A2', 'write-60-80-words')],
        },
        {
            'title': 'The best way to practice vocabulary',
            'instructions': 'What is the best way to practice vocabulary? Give your opinion and support it.',
            'level_code': 'A2',
            'exercise_type': 'opinion',
            'topic': 'learning',
            'output_format': 'short-paragraph',
            'pedagogical_goal': 'Present a short opinion with connected reasoning.',
            'grammar_focus': 'because, but, so',
            'writing_function': 'justify',
            'difficulty_score': 2,
            'word_count_min': 60,
            'word_count_max': 80,
            'estimated_time_minutes': 8,
            'tone': 'neutral',
            'rotation_group': 'daily_opinion',
            'constraints': [('A2', 'give-2-reasons'), ('A2', 'use-because-but-so')],
        },
        {
            'title': 'Travel by train or by bus',
            'instructions': 'Compare traveling by train and by bus, then choose the option you prefer.',
            'level_code': 'A2',
            'exercise_type': 'compare-and-choose',
            'topic': 'travel',
            'output_format': 'comparison-paragraph',
            'pedagogical_goal': 'Practice comparison writing with reasons and an example.',
            'grammar_focus': 'because, but, so',
            'writing_function': 'compare',
            'difficulty_score': 2,
            'word_count_min': 60,
            'word_count_max': 80,
            'estimated_time_minutes': 8,
            'tone': 'neutral',
            'rotation_group': 'daily_compare',
            'constraints': [('A2', 'give-2-reasons'), ('A2', 'include-one-example')],
        },
        {
            'title': 'Should schools give less homework?',
            'instructions': 'Write a short debate paragraph answering this question: should schools give less homework?',
            'level_code': 'B1',
            'exercise_type': 'debate',
            'topic': 'school',
            'output_format': 'short-paragraph',
            'pedagogical_goal': 'Develop basic argumentation with a clear conclusion.',
            'grammar_focus': 'present simple',
            'writing_function': 'argue',
            'difficulty_score': 3,
            'word_count_min': 80,
            'word_count_max': 120,
            'estimated_time_minutes': 10,
            'tone': 'argumentative',
            'rotation_group': 'daily_debate',
            'constraints': [('B1', 'defend-one-side'), ('B1', 'add-a-conclusion-sentence')],
        },
        {
            'title': 'A conversation that changed my mind',
            'instructions': 'Write a short story about a conversation that changed your opinion about something.',
            'level_code': 'B1',
            'exercise_type': 'storytelling',
            'topic': 'feelings',
            'output_format': 'short-story',
            'pedagogical_goal': 'Narrate a personal change of perspective with clear sequence.',
            'grammar_focus': 'past simple and present perfect',
            'writing_function': 'narrate',
            'difficulty_score': 3,
            'word_count_min': 80,
            'word_count_max': 120,
            'estimated_time_minutes': 10,
            'tone': 'reflective',
            'rotation_group': 'daily_story',
            'constraints': [('B1', 'use-past-simple-and-present-perfect'), ('B1', 'write-80-120-words')],
        },
        {
            'title': 'Rewrite a weak opinion paragraph',
            'instructions': 'Rewrite a weak opinion paragraph so it becomes clearer, more organized, and more convincing.',
            'level_code': 'B1',
            'exercise_type': 'reformulation',
            'topic': 'technology',
            'output_format': 'corrected-text',
            'pedagogical_goal': 'Improve organization and clarity through rewriting.',
            'grammar_focus': 'basic connectors',
            'writing_function': 'reformulate',
            'difficulty_score': 3,
            'word_count_min': 80,
            'word_count_max': 120,
            'estimated_time_minutes': 10,
            'tone': 'neutral',
            'rotation_group': 'daily_rewrite',
            'constraints': [('B1', 'add-a-conclusion-sentence')],
        },
        {
            'title': 'A difficult decision at work or school',
            'instructions': 'Reflect on a difficult decision you had to make at work or school and explain the result.',
            'level_code': 'B1',
            'exercise_type': 'reflection',
            'topic': 'work',
            'output_format': 'mini-journal',
            'pedagogical_goal': 'Reflect on a decision using contrast and conclusion.',
            'grammar_focus': 'past simple',
            'writing_function': 'reflect',
            'difficulty_score': 3,
            'word_count_min': 80,
            'word_count_max': 120,
            'estimated_time_minutes': 10,
            'tone': 'reflective',
            'rotation_group': 'daily_reflection',
            'constraints': [('B1', 'include-a-counter-idea'), ('B1', 'add-a-conclusion-sentence')],
        },
        {
            'title': 'Email asking for information about a course',
            'instructions': 'Write an email asking for information about an English course you want to join.',
            'level_code': 'B1',
            'exercise_type': 'email',
            'topic': 'learning',
            'output_format': 'email',
            'pedagogical_goal': 'Write a more complete functional email with clear purpose.',
            'grammar_focus': 'present simple',
            'writing_function': 'request',
            'difficulty_score': 3,
            'word_count_min': 80,
            'word_count_max': 120,
            'estimated_time_minutes': 10,
            'tone': 'formal',
            'rotation_group': 'daily_email',
            'constraints': [('B1', 'write-in-email-format'), ('B1', 'add-a-conclusion-sentence')],
        },
        {
            'title': 'A problem during a trip',
            'instructions': 'Describe a problem you had during a trip and explain how you solved it.',
            'level_code': 'B1',
            'exercise_type': 'scenario-writing',
            'topic': 'travel',
            'output_format': 'short-paragraph',
            'pedagogical_goal': 'Narrate and resolve a practical problem clearly.',
            'grammar_focus': 'past simple and present perfect',
            'writing_function': 'narrate',
            'difficulty_score': 3,
            'word_count_min': 80,
            'word_count_max': 120,
            'estimated_time_minutes': 10,
            'tone': 'neutral',
            'rotation_group': 'daily_scenario',
            'constraints': [('B1', 'use-past-simple-and-present-perfect'), ('B1', 'write-80-120-words')],
        },
        {
            'title': 'Summarize advice for healthy habits',
            'instructions': 'Write a short summary of advice for healthy habits and explain the main idea.',
            'level_code': 'B1',
            'exercise_type': 'summary',
            'topic': 'personal-habits',
            'output_format': 'summary',
            'pedagogical_goal': 'Summarize key advice in a short organized text.',
            'grammar_focus': 'present simple',
            'writing_function': 'summarize',
            'difficulty_score': 3,
            'word_count_min': 80,
            'word_count_max': 110,
            'estimated_time_minutes': 9,
            'tone': 'neutral',
            'rotation_group': 'daily_summary',
            'constraints': [('B1', 'add-a-conclusion-sentence')],
        },
        {
            'title': 'One advantage, one drawback',
            'instructions': 'Choose one piece of technology and write about one advantage and one drawback before giving your opinion.',
            'level_code': 'B1',
            'exercise_type': 'counterargument',
            'topic': 'technology',
            'output_format': 'short-paragraph',
            'pedagogical_goal': 'Practice balanced argumentation with a counter idea.',
            'grammar_focus': 'basic connectors',
            'writing_function': 'argue',
            'difficulty_score': 3,
            'word_count_min': 80,
            'word_count_max': 120,
            'estimated_time_minutes': 10,
            'tone': 'argumentative',
            'rotation_group': 'daily_counterargument',
            'constraints': [('B1', 'defend-one-side'), ('B1', 'include-a-counter-idea')],
        },
    ]

    for exercise_data in exercises:
        level = levels[exercise_data['level_code']]
        exercise_type = exercise_types[exercise_data['exercise_type']]
        topic = topics[exercise_data['topic']]
        output_format = output_formats[exercise_data['output_format']]
        constraint_keys = exercise_data.pop('constraints')
        title = exercise_data['title']

        exercise, _ = Exercise.objects.update_or_create(
            title=title,
            level=level,
            defaults={
                'instructions': exercise_data['instructions'],
                'exercise_type': exercise_type,
                'topic': topic,
                'output_format': output_format,
                'pedagogical_goal': exercise_data['pedagogical_goal'],
                'grammar_focus': exercise_data['grammar_focus'],
                'writing_function': exercise_data['writing_function'],
                'difficulty_score': exercise_data['difficulty_score'],
                'word_count_min': exercise_data['word_count_min'],
                'word_count_max': exercise_data['word_count_max'],
                'estimated_time_minutes': exercise_data['estimated_time_minutes'],
                'tone': exercise_data['tone'],
                'rotation_group': exercise_data['rotation_group'],
                'is_active': True,
            },
        )
        ExerciseConstraint.objects.filter(exercise=exercise).delete()
        for constraint_key in constraint_keys:
            ExerciseConstraint.objects.create(
                exercise=exercise,
                constraint=constraints[constraint_key],
            )

    DailyChallenge.objects.all().delete()


def unseed_exercises_batch_2(apps, schema_editor):
    DailyChallenge = apps.get_model('fluency', 'DailyChallenge')
    Exercise = apps.get_model('fluency', 'Exercise')

    DailyChallenge.objects.all().delete()
    Exercise.objects.filter(
        title__in=[
            'My favorite place at home',
            'A good snack for school',
            'Three things in my bag',
            'My best weekday habit',
            'A family member I admire',
            'What I do after dinner',
            'Three words about my city',
            'A hobby I enjoy',
            'Study alone or with friends',
            'A useful app for students',
            'My neighborhood in the evening',
            'An email to invite a friend',
            'A day I felt proud',
            'You missed the bus',
            'The best way to practice vocabulary',
            'Travel by train or by bus',
            'Should schools give less homework?',
            'A conversation that changed my mind',
            'Rewrite a weak opinion paragraph',
            'A difficult decision at work or school',
            'Email asking for information about a course',
            'A problem during a trip',
            'Summarize advice for healthy habits',
            'One advantage, one drawback',
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('fluency', '0003_seed_exercises'),
    ]

    operations = [
        migrations.RunPython(seed_exercises_batch_2, unseed_exercises_batch_2),
    ]
